import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
const fontPoppins = Poppins({
  subsets: ['latin'],
  weight: "100"
});


export const metadata: Metadata = {
  title: "Shorten Url",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontPoppins.className}>
      <body className="overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
